language: node_js
node_js:
    - node
env:
    - WebSocketURI=wss://8fxyeftwqd.execute-api.eu-central-1.amazonaws.com/SPU
before_install:
    - export TZ=Europe/Zurich
before_deploy: yarn build
deploy:
    provider: s3
    access_key_id: AKIASUS73RVHABZMCGGS
    secret_access_key:
        secure: kEGcvc0a+mA3ry5tJOyxJoZTJmCAd+LVPJ3hUc7cuSYYxB94l5gFgOYzKmleybzEFXg79dsHbwNAza4p1BMPtcvhjcEOWOuoESCCWv33jl6vB9ACjXjcC2ZAhTTIZkzvK/wdDCUwkXgCzxMqh9vl7dYjob+FYybdlgNihDjv9lxkLKRFv+HHUprk9aKPIqHVDt3Xpt8eGuLnQzCW9rmII77ryR+yNCjwcBeCKockBFezNyIxq+J0PzJlUX55dAAPiki8ve3rfdB96mYLx95FVdtsdNDDdf78RoIArr8adeSPtrA98xSrzdZMGcykxvCQo4Tzx+zHMrlQpmB7lGm05p/7HmPqtztfCOVyMLeq4wVSg7LjxSs9dQ8LsPcrQoCN3N82EMYKA7xfFYRkIhvxsGKigmSsk3tLMiEkr5LNdrCHaqH67NgxExKG8vVqzMXD7CXFEUlT9vLG2vudmzKDzKUP+Lj+jifayQ0RcRiMf6LJ+0n/K5iTGNKefBsCGnjMbBRBhep53asKFW3I0OGOpkUlP/AF/qECd772tD7cmSxppd3M9TpejFPfh7PPKj0VgHnMLwbgrP3BbYhTNzx97vYHA4ObT9UQ24lWLAAd1eDemvvxi2vScRt13HeRru+hxZ0pf2N8zLsUEPcnkpB5UOgvvVt1uMmWdhB+8Gb9vuM=
    bucket: processing-unit
    acl: public_read
    skip_cleanup: true
    region: eu-north-1
    local_dir: dist
    on:
        repo: shared-processing-unit/spu-processing-unit
