language: node_js
node_js:
    - node
env:
    - WebSocketURI=wss://8g3zju6pe2.execute-api.eu-central-1.amazonaws.com/Prod
before_install:
    - export TZ=Europe/Zurich
before_deploy: yarn build
deploy:
    provider: s3
    access_key_id: AKIASUS73RVHIMYZQ3O5
    secret_access_key:
        secure: Bv9pXybin6RAxAPfhb3+xyLWzsDqW0A0axah/dbgNAQ37ACdYUKIuLwb0s58V80OCc9gEs3BRapd9nrOtTGOQInIoQ1yHNSLwHT3LZJJG73EcazOdraHT8GeK5rCN3qL8LRAkZCkOb7b1yhc8IhecLSA9VjlQaFQ429o9Sf1bSMA9OKGfDzovlI+RY3nqk2AoF4MVd2EJ7YGA6n48JtqXWb9dVH8Yf9DqQwV54ak/BNT3hg33l45hSpyrCUlSGLCg6PcLuOInl9JTopAGsXqQKLNsQpVDn7OJy8kLtOchd5Hrvat4nhcJMrW77JTHkxrvYXjDVvf2pMgRL8VEuyQL3tlioI6EpqpuvkXeWVo8IuNCj7gezrJaWWCM5igHVqmkfoXj2rxIzctTCxVRLsSxqn3rnHKpJWW2XJV6Kv+BYso9MTpbLX0OPPA0hUge8cIv1+giHENUtfkP3BDeye32DrLgHU58XahseZJgp7Oe4F5Rmjv2U6v6qVN/UCI5hfhT5EJi+hRHE9qPS5TWcvb8d40b6fOZcvC6/J91oBxozvxHMR1ROO5L2sV3KzMpGSoYLMwLTuhLPSFs/xHZisMRIEHUpsoeVmIx3Zco2T1Dq0KvUZYF2c6jz5AgeIISLhMpCjScTIPll0FmdaZNHoxLidkEJsoulQp64ssvVQNdbI=
    bucket: processing-unit
    acl: public_read
    skip_cleanup: true
    region: eu-north-1
    local_dir: dist
    on:
        repo: rkram3r/spu-processing-unit
